name: Deploy Almoxarifado Multi-Server

on:
  push:
    branches: [ "master" ]

concurrency:
  group: deploy-almoxarifado
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false 
      matrix:
        include:
          - server_name: "Servidor Principal"
            host_secret: SSH_HOST
            user_secret: SSH_USER
            key_secret: SSH_PRIVATE_KEY
            
          - server_name: "Servidor Rafael"
            host_secret: SSH_HOST_RAFAEL
            user_secret: SSH_USER_RAFAEL
            key_secret: SSH_PRIVATE_KEY_RAFAEL

    name: Deploy em ${{ matrix.server_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Adicionar servidor aos known_hosts
        run: |
          mkdir -p ~/.ssh
      
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets[matrix.host_secret] }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy remoto
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets[matrix.host_secret] }}
          username: ${{ secrets[matrix.user_secret] }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets[matrix.key_secret] }}
          script: |
            set -e
            echo "backup simples"
            sudo /usr/local/bin/backup_almoxarifado.sh
            echo "==> Conectado em: ${{ matrix.server_name }}"
            echo "==> Acionando script local"
            
            sudo /usr/local/bin/deploy_almoxarifado.sh